config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  get "attendees/new"
  get "attendees/create"

  get "attending_events", to: "users#attending_events"

  get "invited_events", to: "users#invited_events"

  patch "update_invite_status", to: "invitiations#update_invite_status"

  devise_for :users

  resources :users, only: [] do
    resources :events, only: [ :index, :edit, :update, :destroy ]
  end
  resources :events do
    resources :attendees, only: [ :new, :create, :destroy ]
    resources :invitiations, only: [ :new, :create, :destroy ]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.htm
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :attendees
  has_many :users, through: :attendees
  has_many :invitiations
  has_many :invited_users, through: :invitiations, source: :user
end

app/models/invitiation.rb
class Invitiation < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events

  has_many :attendees
  has_many :attending_events, through: :attendees, source: :event

  has_many :invitiations
  has_many :invited_events, through: :invitiations, source: :event
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :username, uniqueness: true, presence: true
  validates :name, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:email, :password)
    end
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:username, :name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |user_params|
      user_params.permit(:username, :name, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  def create
    attendee = Attendee.new(user_id: current_user.id, event_id: params[:event_id])
    if attendee.save
      redirect_to Event.find_by(id: params[:event_id]), notice: "Succefully reserved a spot."
    else
      redirect_to root_path, notice: "Failed to reserve a spot."
    end
  end

  def destroy
    event = Event.find_by(id: params[:event_id])
    user = User.find_by(id: params[:user_id])

    if event.users.include?(user)
      event.users.destroy(user)
    end
    redirect_to event
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [ :index, :show ]
  before_action :authorize_user, only: [ :edit, :update, :destroy ]
  def index
    if params[:user_id]
      @events = Event.where(user_id: params[:user_id])
    else
      @events = Event.where(private: false)
    end
  end

  def show
    @event = Event.find_by(id: params[:id])
    @attendees = @event.users
    @invitations = @event.invitiations
  end

  def new
    @event = current_user.events.build
  end

  def create
    event = current_user.events.create(event_params)
    if event.save
      redirect_to event
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find_by(id: params[:id])
  end

  def update
    event = Event.find_by(id: params[:id])
    if event.update!(event_params)
      redirect_to event
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    event = Event.find_by(id: params[:id])
    if event.present?
      event.destroy
    end
    redirect_to root_path
  end

  private
  def event_params
    params.require(:event).permit(:title, :description, :private)
  end

  def authorize_user
    event = Event.find_by(id: params[:id])

    if event.nil? || event.user_id != current_user.id
      flash[:notice] = "This event does not belong to you."
      redirect_to root_path
    end
  end
end

app/controllers/invitiations_controller.rb
class InvitiationsController < ApplicationController
  before_action :authenticate_user!
  def new
    @event = Event.find_by(id: params[:event_id])
    @invitation = Invitiation.new
  end
  def create
    event = Event.find_by(id: params[:event_id])
    user = User.find_by(username: params[:username])

    unless current_user == user || event.invited_users.include?(user)
      invitiation = Invitiation.new(user_id: user.id, event_id: params[:event_id]) unless user == current_user

      if invitiation.save
        redirect_to event, notice: "Succefully invited #{user.name}."
      end
    else
      redirect_to event, notice: "Failed to send invite."
    end
  end

  def destroy
    event = Event.find_by(id: params[:event_id])
    user = User.find_by(id: params[:user_id])
    if event.invited_users.include?(user)
      event.invited_users.destroy(user)
    end
    redirect_to event
  end

  def update_invite_status
    invite = Invitiation.find_by(id: params[:id])
    invite.update(status: params[:status])

    if params[:status] == "Accept"
      attendee = current_user.attendees.new(user_id: current_user.id, event_id: params[:event_id])
      if attendee.save
        redirect_to Event.find_by(id: params[:event_id])
      else
        redirect_to root_path
      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @user = current_user if user_signed_in?
  end

  def users_events
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def attending_events
    @events = current_user.attending_events
  end

  def invited_events
    @invitations = current_user.invitiations
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def get_user_by_id(user_id)
    User.find_by(id: user_id).name
  end

  def belongs_to_user?(event)
    !current_user.nil? && !event.nil? && event.user_id == current_user.id
  end

  def attending_event?(event)
    event.users.include?(current_user)
  end
end

app/helpers/invitiations_helper.rb
module InvitiationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def get_event_info(event_id)
    Event.find_by(id: event_id)
  end
end

app/views/attendees/create.html.erb
<h1>Attendees#create</h1>
<p>Find me in app/views/attendees/create.html.erb</p>

app/views/events/_event_form.html.erb
<div class="event_form">
    <%= form_with model: @event do |f| %>
    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>
    <div>
        <%= f.label :description %>
        <%= f.text_area :description %>
    </div>
    <div>
        <%= f.label :private %>
        <%= f.check_box :private %>
    </div>
    <%= f.submit%>
    <% end %>
</div>

app/views/events/edit.html.erb
<%= render "event_form" %>

app/views/events/index.html.erb
<% if @events.any? %>
<div class="events-list">
    <% @events.each do |event| %>
      <%= render partial: "shared/event", locals: {event: event} %>
    <% end %>
</div>
<% else %>
<p>No events found.</p>
<% end %>

app/views/events/new.html.erb
<%= render "event_form" %>

app/views/events/show.html.erb
<%= render partial: "shared/event", locals:{event: @event} %>
<%= button_to "Home", root_path, method: :get %>
<% if belongs_to_user?(@event) %>
    <%= button_to "Edit Event", edit_event_path(@event), method: :get %>
    <%= button_to "Delete Event", @event, method: :delete %>
    <%= button_to "Invite User", new_event_invitiation_path(event_id: @event.id), method: :get %>
<% elsif user_signed_in? && attending_event?(@event) %>
    <%= button_to "Remove Reservation", event_attendee_path(event_id: @event.id, user_id: current_user.id), method: :delete %>
<% elsif user_signed_in? %>
    <%= button_to "Attend Event", event_attendees_path(event_id: @event.id), method: :post %>
<% end %>

<% if @attendees.length > 0 %>
    <p>Attendees</p>
    <% if belongs_to_user?(@event) %>
        <p>Click on the user to remove them from the event.</p>
    <% end %>
    <ol>
        <% @attendees.each do |attendee| %>
            <li><%= attendee.name %></li>
            <% if belongs_to_user?(@event) %>
                <%= button_to "Remove #{attendee.name}", event_attendee_path(event_id: @event.id, user_id: attendee.id), method: :delete %>
            <% end %>
        <% end %>
    </ol>
<% end %>
<br>
<% if @invitations.length > 0%>
    <p>Invited Users</p>
    <% if belongs_to_user?(@event) %>
        <p>Click the button to un-invite a user from the event.</p>
    <% end %>
    <ol>
        <% @invitations.each do |invite| %>
            <li><%= get_user_by_id(invite.user_id) %> <br> Status: <%=invite.status%></li>
            <% if belongs_to_user?(@event) %>
                <%= button_to "Un-invite", event_invitiation_path(event_id: @event.id, user_id: invite.user_id), method: :delete %>
            <% end %>
        <% end %>
    </ol>
<% end %>

app/views/invitiations/new.html.erb
<%= form_with url: event_invitiations_path(event_id: @event.id), method: :post do |f|%>
    <div>
        <%= f.hidden_field :event_id, value: @event.id %>
    </div>
    <div>
        <%= f.label :username %>
        <%= f.text_field :username %>
    </div>
    <%= f.submit "Invite User" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Meetup Clone" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<% if user_signed_in?%>
    <%= render "/shared/user" %>
    <%= button_to "Sign Out", destroy_user_session_path, method: :delete %>
    <%= button_to "Edit", edit_user_registration_path, method: :get %>
    <%= button_to "Create Event", new_event_path, method: :get %>
    <%= button_to "View Your Events", user_events_path(@user), method: :get %>
    <%= button_to "Reserved Spots", attending_events_path, method: :get %>
    <%= button_to "Invited Events", invited_events_path, method: :get %>
<%else%>
    <%= button_to "Sign In", new_user_session_path, method: :get %>
<% end %>
<%= button_to "View All Events", events_path, method: :get %>

app/views/shared/_event.html.erb
<div class="event">
    <%= link_to event do %>
        <h3><%= event.title %></h3>
    <%end%>
    <p>Created by: <%= get_user_by_id(event.user_id) %></p>
    <p><%= event.description%></p>
    <p>Is Private: <%= event.private %></p>
</div>

app/views/shared/_user.html.erb
<div class="user">
    <h3><%= @user.name%></h3>
    <p><%= @user.username%></p>
</div>

app/views/users/attending_events.html.erb
<p>Events you are attending</p>
<% if @events.any? %>
<div class="events-list">
    <% @events.each do |event| %>
      <%= render partial: "shared/event", locals: {event: event} %>
    <% end %>
</div>
<% else %>
<p>No events found.</p>
<% end %>

app/views/users/invited_events.html.erb
<p>Events you are invited to.</p>
<% if @invitations.any? %>
<div class="events-list">
    <% @invitations.each do |invite| %>
      <%= render partial: "shared/event", locals: {event: get_event_info(invite.event_id)} %>
      <%= button_to "Accept", update_invite_status_path(id: invite.id, status: "Accept", event_id: invite.event_id), method: :patch %>
      <%= button_to "Decline", update_invite_status_path(id: invite.id, status: "Decline"), method: :patch %>
    <% end %>
</div>
<% else %>
<p>No events found.</p>
<% end %>